import { GoogleGenAI } from "@google/genai";

// Initialize GoogleGenAI client (New SDK)
const genAI = new GoogleGenAI({ apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY || process.env.GEMINI_API_KEY });

export const maxDuration = 60;

export async function POST(req: Request) {
    try {
        const { image, product } = await req.json();

        if (!image || !product) {
            return Response.json({ error: 'Missing image or product data' }, { status: 400 });
        }

        console.log(`Starting Try-On for: ${product.title}`);

        // 1. Process User Image (Base64)
        // Ensure strictly base64 string
        const userImageBase64 = image.includes(',') ? image.split(',')[1] : image;

        // 2. Fetch Product Image (URL -> Base64)
        let productImageBase64 = null;
        if (product.image) {
            try {
                console.log(`Fetching product image from: ${product.image}`);
                const imgRes = await fetch(product.image);
                if (!imgRes.ok) throw new Error(`Failed to fetch product image: ${imgRes.statusText}`);
                const arrayBuffer = await imgRes.arrayBuffer();
                productImageBase64 = Buffer.from(arrayBuffer).toString('base64');
            } catch (err) {
                console.error("Failed to fetch product image:", err);
                // Fallback? If we can't get the product image, the model can't "see" it.
                // We could rely on description only, but User Prompt says "Attached photo of product".
                // We'll proceed with just description if image fails, but warn.
            }
        }

        // 3. Construct Prompt (Exact User Request)
        const promptText = `Вот фото как выглядит автор, фото приложено. Так же приложено фото товара и наименование товара, запоминая как выглядит товар, надень ее на автора, не меняя ничего на его кадре кроме его одежды. Наименование товара: ${product.title}. ${product.brand ? `Бренд: ${product.brand}.` : ''}`;

        // 4. Prepare Context
        const contents = [
            { text: promptText },
            {
                inlineData: {
                    mimeType: "image/jpeg",
                    data: userImageBase64,
                },
            },
        ];

        // Attach Product Image if available
        if (productImageBase64) {
            contents.push({
                inlineData: {
                    mimeType: "image/jpeg",
                    data: productImageBase64,
                },
            });
        }

        console.log(`Sending request to gemini-3.0-pro-image-preview with ${productImageBase64 ? '2' : '1'} images...`);

        // 5. Generate
        try {
            // Using the specific model requested (and verified in test script)
            const response = await genAI.models.generateContent({
                model: "gemini-3-pro-image-preview",
                contents: contents,
                config: {
                    responseModalities: ['TEXT', 'IMAGE'],
                }
            });

            console.log("Gemini 3 Pro Response Received.");

            let generatedImageBase64 = null;
            let generatedText = "Here is your virtual try-on result!";

            const candidates = response.candidates || (response as any).response?.candidates;

            if (candidates && candidates[0]?.content?.parts) {
                for (const part of candidates[0].content.parts) {
                    if (part.inlineData) {
                        generatedImageBase64 = part.inlineData.data;
                    }
                    if (part.text) {
                        generatedText = part.text;
                    }
                }
            }

            if (generatedImageBase64) {
                return Response.json({
                    type: 'image',
                    result: generatedImageBase64,
                    advice: generatedText
                });
            } else {
                throw new Error("No image data generated by model");
            }

        } catch (genError: any) {
            console.error("Gemini 3 Generation Failed:", genError.message);
            // Retry with Fallback (Gemini 2.5 Flash Image) or just Text
            // We'll try one fallback to 'gemini-2.0-flash-exp' as seen in test script fallback logic, 
            // OR 'gemini-2.5-flash-image' which worked before (but prompt structure is different - 2.5 flash image might EXPECT a prompt differently).
            // Let's stick to error reporting if 3 fails, as user specifically wants 3.

            return Response.json({
                type: 'text',
                advice: `Sorry, I couldn't generate the try-on image right now. Error: ${genError.message}.`,
                error: genError.message
            });
        }

    } catch (error: any) {
        console.error("Try-On API Critical Error:", error);
        return Response.json({ error: "Failed to process try-on request" }, { status: 500 });
    }
}
